_target_: pytorch_lightning.loggers.WandbLogger

project: Bees
entity: kotu-pl
name: ${now:%Y%m%d}_${hydra:job.name}_${hydra:job.override_dirname}
group: multirun_${hydra:parent.id}
save_dir: ${logs_dir}/wandb
dir: ${logs_dir}/wandb

mode: online
job_type: train
log_model: False

tags:
  - bees
  - multirun
