_target_: pytorch_lightning.loggers.WandbLogger

project: Bees
entity: kotu-pl
name: ${now:%Y%m%d}_${hydra:job.override_dirname}_${hydra:job.num}
group: multirun_${hydra:sweep.dir}
save_dir: ${logs_dir}/wandb/${hydra:sweep.subdir}
id: ${uuid:}
resume: never

mode: online
job_type: train
log_model: False

tags:
  - bees
  - multirun
