_target_: pytorch_lightning.loggers.WandbLogger

project: Bees
entity: kotu-pl
id: ${uuid:}
resume: never
reinit: True
save_dir: ${logs_dir}/wandb/${hydra:sweep.subdir}

group: multirun_${sweep_ts}
name: ${network.model.model_name} # sweep_ts: ${basename:${hydra:sweep.dir}} 

mode: online
job_type: train
log_model: False

tags:
  - bees
  - multirun
