_target_: pytorch_lightning.loggers.WandbLogger

project: Bees
entity: kotu-pl
id: ${hydra:job.id}
resume: never
reinit: finish_previous
save_dir: ${logs_dir}/wandb/${hydra:sweep.subdir}

group: taka_to_kupa
#multirun_${oc.env:RUN_TS}
name: ${network.model.model_name}_${hydra:job.num}

mode: online
job_type: train
log_model: False

tags:
  - bees
  - multirun
