hydra:
  output_subdir: null # nie twórz .hydra wewnątrz run‑dir
  job:
    chdir: true # zmień katalog roboczy
  run:
    dir: ${hydra:runtime.cwd}/experiments/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${oc.env:PWD}/experiments/multirun
    subdir: ${now:%Y-%m-%d_%H-%M-%S}

logs_dir: ${hydra:runtime.cwd}/logs

defaults:
  - _self_
  - data: bees_single_unbalanced
  - network: resnet
  - trainer: trainer
  - logger: wandb
  - callbacks:
    - model_checkpoint
    - early_stopping

resnet_version: 34
densenet_version: 121
convnext_version: tiny
efficientnet_version: _b4
mobilenetv3_version: large_100
regnet_version: y_3.2gf
swin_transformer_version: _tiny_patch4_window7_224
vision_transformer_base: deit
vision_transformer_version: small_patch16_224

run_ts: ${now:%Y%m%d%H%M%S}
sweep_ts: ${basename:${hydra:sweep.dir}}
