hydra:
  job:
    chdir: true # zmień katalog roboczy
  run:
    dir: ${hydra:runtime.cwd}/experiments/runs/${oc.env:RUN_TS}/${hydra:job.num}
  sweep:
    dir: ${oc.env:PWD}/experiments/multirun/${oc.env:RUN_TS}
    subdir: ${hydra:job.num}

logs_dir: ${hydra:runtime.cwd}/logs

defaults:
  - _self_
  - data: bees_multi_label
  - network: resnet
  - trainer: trainer
  - logger: wandb
  - callbacks:
    - model_checkpoint
    - early_stopping

resnet_version: 34
densenet_version: 121
convnext_version: tiny
efficientnet_version: _b4
mobilenetv3_version: large_100
regnet_version: y_3.2gf
swin_transformer_version: _tiny_patch4_window7_224
vision_transformer_base: deit
vision_transformer_version: small_patch16_224
