model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_loss
  dirpath: ${logs_dir}/checkpoints
  filename: model-{epoch:02d}-{val_loss:.2f}
  save_top_k: 3
  mode: min
