model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_mean_ap
  dirpath: ${logs_dir}/checkpoints
  filename: model-{epoch:02d}-{val_loss:.2f}
  mode: max
  save_top_k: 1
  save_last: true
