_target_: classification.lightning_modules.generic_timm_model.GenericTimmLitModel

model:
  _target_: timm.create_model
  model_name: densenet121
  pretrained: True
  num_classes: 5

learning_rate: 1e-3
