_target_: classification.lightning_modules.generic_timm_model.GenericTimmLitModel

model:
  _target_: timm.create_model
  model_name: efficientnet${efficientnet_version}
  pretrained: True
  num_classes: 5

learning_rate: 1e-3
freeze_backbone: True
