_target_: classification.lightning_modules.transfer_resnet.TransferResNetLitModel

version: 18

model: 
  _target_: torchvision.models.resnet${..version}
  pretrained: True

learning_rate: 1e-3
num_classes: 5
