_target_: pytorch_lightning.Trainer
max_epochs: 50
logger: ${logger}
callbacks:
  - ${callbacks.model_checkpoint}
  - ${callbacks.early_stopping}
  - ${callbacks.backbone_finetuning}
  - ${callbacks.ema}
